### ISSUE TITLE
rmr2 does not work on Mac OS X 10.7.5

### ISSUE THREAD

**Issue by ViraSem** [RevolutionAnalytics/RHadoop#220]
Hello!

I am following these instructions https://github.com/RevolutionAnalytics/RHadoop/wiki/user%3Ermr%3EHome 
and can't get rmr2 installed on my mac. Steps 1-3 are done and environmental variables (step 5) are also set. However, when I run in the terminal:

R CMD INSTALL  /Users/virasemenova/Desktop/rmr2

I get the error message:

* installing to library ‘/Library/Frameworks/R.framework/Versions/3.1/Resources/library’
* installing *source* package ‘rmr2’ ...
** libs
sh: make: command not found
ERROR: compilation failed for package ‘rmr2’
* removing ‘/Library/Frameworks/R.framework/Versions/3.1/Resources/library/rmr2’

Please help!
